### ISSUE TITLE
Some images were removed from imgur

### ISSUE THREAD

**Issue by ymmshi** [facebookresearch/IMGUR5K-Handwriting-Dataset#10]
2021.11.24 

For IMG: lRgjZ, ref hash: c64945bd74c067f29e01f2f3b5eeff60 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: NeVsJy7, ref hash: 924eb5398cea242b01f43e73b1a12811 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 7IUPrpZ, ref hash: 3e4f912a1e9d91c35c68c0880826e680 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: hdZPXS2, ref hash: 40f094f7bf1e56ed56cc2fcb8adcff14 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: Nokn65F, ref hash: 8ef5355846c5806d280a7ef563bc3f45 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: hwq46gA, ref hash: 8c27046ac37905291bbd9cb2cec72241 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: xBG71ye, ref hash: 9a7ea2e2e5c1ee3f5da627af7d253f09 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: KSSvYJH, ref hash: f7f71a1646fbdba638eca0365f09cff6 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: nUnLGVR, ref hash: 0e8e826cb85b53f5a459c0f0eed36d4f != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: PFTXe3d, ref hash: 1f372a9c9fc035ff0b57a4f21e070b9c != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: fa3NgTS, ref hash: 616f5801a0bdbdacf26e78536641a860 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: pyXUSxO, ref hash: ea7b303e76d47ce8555286f67bccad5b != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: GjgtyBl, ref hash: b6980d39ce80b2a3085cd89c537327b7 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: Cs0smsA, ref hash: ac942db4d0071e882db20dbca2de8d5d != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: kHgtG4H, ref hash: 532bf487cee2a3266f6985ce322626f2 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: kyRKrOy, ref hash: 79dab6bff97aa22fb8aac47676dd150f != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 91V1uHF, ref hash: 6fd3da585984de869c9e3f85ab96fd72 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 1IYlYlq, ref hash: 641076db3f95efea3fb35782777dabaf != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: sAOdjXq, ref hash: 730fd6033c8f255d4f1774b2d049922e != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: mlmRA89, ref hash: cb2b6705e71a3f8fb4ca29640b3de230 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 3TIryzT, ref hash: fef7718a45ee39d5ab324a0d792f8ee0 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: pldp0ke, ref hash: 7cbd0528faa5018e08d4e08834ebc8ab != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: s7WGXwr, ref hash: 6c25277ca43925cd93eac806fb646937 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: HIAwuPd, ref hash: 150c87bb0dc4d7819abf46807eafbf39 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: DGafbuR, ref hash: 212a52ab552f75a6d4655e07865188c0 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: PPqWkdx, ref hash: d8c4a27288f0c4db3a716dc3fd06dee2 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 03IJytp, ref hash: 9ff28f403eac64b136006a5c86a49c84 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: pjRXC0f, ref hash: 36016c1784a21f092f26e78c27c7d064 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 6De62VB, ref hash: 3ad6e31174112f63b633db85644238a0 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: 00Wo8nQ, ref hash: 7cedb0a7914a5336d2de9a21a58eb788 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: bX1Ajfi, ref hash: d7cfd20cddfe6a9fee3b9bea5e1f6564 != cur hash: d835884373f4d6c8f24742ceabe74946
For IMG: Idip0tp, ref hash: 8785533373eb588fd1e49a7537894692 != cur hash: d835884373f4d6c8f24742ceabe74946

**Comment by kris314** [comment]
Hi ymmshi,

This is bound to happen as the images are retrieved from IMGUR website every time you run the script. 

Please read the disclaimer in the readme file to know more on this.

Thanks
