### ISSUE TITLE
Licensing for commercial use?

### ISSUE THREAD

**Issue by Luux** [facebookresearch/IMGUR5K-Handwriting-Dataset#6]
Hello,

we would like to use the dataset as additional training data for our OCR model. However, the current license does not allow to use the data for commercial purpose. Is it possible to license the dataset as a company for such purposes? If so, who can we contact in that regard? Or is this not possible because of the imgur origin of the data?

**Comment by kris314** [comment]
Thanks for showing interest in our dataset. However, the dataset usage as per license restricts any commercial usages.
