### ISSUE TITLE
Can't understand box format

### ISSUE THREAD

**Issue by Kakoedlinnoeslovo** [facebookresearch/IMGUR5K-Handwriting-Dataset#7]
Hello, thank you for sharing the dataset! It looks like hard work has been done!  👋👋👋
I have one question about annotations: I can't understand the format of the bboxes: bounding_box in xywha format? 
What means "a" at the end?
I know three popular formats: pascal_voc [x_min, y_min, x_max, y_max]; coco  [x_min, y_min, width, height];  yolo [x_center, y_center, width, height], x_center and y_center are the normalized coordinates; https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/
But I can't find any "a" in them. Can you please help me to understand this moment!

**Comment by yeyingdege** [comment]
Hi, I plotted the annotated bounding box on corresponding images just using [x, y, x+w, y+h]. But they are not aligned. Maybe I should use "a", but I don't know how. Could you explain how to convert xywha to [x_min, y_min, x_max, y_max]? Thank you very much.

**Comment by felixdittrich92** [comment]
@yeyingdege 
Take a look at this:
[Imgur5k example](https://www.kaggle.com/ayuraj/investigate-imgur5k-dataset)

**Comment by kris314** [comment]
Hi
Apologies for a late response.

The annotation format details are updated in the Readme.

The bounding_box is in (xc,yc,w,h,a) format in absolute floating points coordinates. 
Here:
- (xc, yc) is the center of the rotated box
- (w, h) is the width and height
- (a) is the angle in degrees counterclockwise

Below is a python code snippet to convert the above format to axis parallel rectangle coordinates:

input (xc,yc,w,h,a)
output (x_min, y_min, x_max, y_max)

```
new_w = w * math.cos(a* (math.pi/180)) + h * math.sin(a* (math.pi/180))
new_h = h * math.cos(a* (math.pi/180)) + w * math.sin(a* (math.pi/180))

x_min = math.floor(xc - new_w/2)
y_min = math.floor(yc - new_h/2)
x_max = math.floor(x_min+new_w)
y_max = math.floor(y_min+new_h)
```

Thanks

**Comment by kris314** [comment]
> @yeyingdege Take a look at this: [Imgur5k example](https://www.kaggle.com/ayuraj/investigate-imgur5k-dataset)

I don't see the angle information being used in this codebase. This would result in incorrect bounding boxes for rotated words. The example of such wrong plotting is also shown in their notebook.

**Comment by yeyingdege** [comment]
> Hi Apologies for a late response.
> 
> The annotation format details are updated in the Readme.
> 
> The bounding_box is in (xc,yc,w,h,a) format in absolute floating points coordinates. Here:
> 
> * (xc, yc) is the center of the rotated box
> * (w, h) is the width and height
> * (a) is the angle in degrees counterclockwise
> 
> Below is a python code snippet to convert the above format to axis parallel rectangle coordinates:
> 
> input (xc,yc,w,h,a) output (x_min, y_min, x_max, y_max)
> 
> ```
> new_w = w * math.cos(a* (math.pi/180)) + h * math.sin(a* (math.pi/180))
> new_h = h * math.cos(a* (math.pi/180)) + w * math.sin(a* (math.pi/180))
> 
> x_min = math.floor(xc - new_w/2)
> y_min = math.floor(yc - new_h/2)
> x_max = math.floor(X1+new_w)
> y_max = math.floor(Y1+new_h)
> ```
> 
> Thanks

It works. Thank you. I guess "X1" and "Y1" should be "x_min" and "y_min" respectively.

**Comment by kris314** [comment]
> > Hi Apologies for a late response.
> > The annotation format details are updated in the Readme.
> > The bounding_box is in (xc,yc,w,h,a) format in absolute floating points coordinates. Here:
> > 
> > * (xc, yc) is the center of the rotated box
> > * (w, h) is the width and height
> > * (a) is the angle in degrees counterclockwise
> > 
> > Below is a python code snippet to convert the above format to axis parallel rectangle coordinates:
> > input (xc,yc,w,h,a) output (x_min, y_min, x_max, y_max)
> > ```
> > new_w = w * math.cos(a* (math.pi/180)) + h * math.sin(a* (math.pi/180))
> > new_h = h * math.cos(a* (math.pi/180)) + w * math.sin(a* (math.pi/180))
> > 
> > x_min = math.floor(xc - new_w/2)
> > y_min = math.floor(yc - new_h/2)
> > x_max = math.floor(X1+new_w)
> > y_max = math.floor(Y1+new_h)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks
> 
> It works. Thank you. I guess "X1" and "Y1" should be "x_min" and "y_min" respectively.

Yes. I just my updated the previous comment. 

Thank you !

**Comment by felixdittrich92** [comment]
@kris314 
I have tested your suggestion and some rotated boxes are not plotted correct.
@yeyingdege 
following will work correctly:
```
img_names = os.listdir(img_folder)

with open(label_path) as f:
      annotation_file = json.load(f)

for img_name in img_names:
     img_path = Path(img_folder, img_name)
     img_id = img_name.split(".")[0]

    # some files have no annotations
    if img_id not in annotation_file['index_to_ann_map'].keys():
            continue

    ann_ids = annotation_file['index_to_ann_map'][img_id]
    annotations = [annotation_file['ann_id'][a_id] for a_id in ann_ids]

    labels: List[str] = []
    box_targets: List[np.ndarray] = []
    for ann in annotations:
          if ann['word'] != '.':
                labels.append(ann['word'])
                # x_center, y_center, width, height, angle
                _box = [float(val) for val in ann['bounding_box'].strip('[ ]').split(', ')]
                # (x, y) coordinates of top left, top right, bottom right, bottom left corners
                box_targets.append(cv2.boxPoints(((_box[0], _box[1]), (_box[2], _box[3]), _box[4])))

          if not use_polygons:
              # xmin, ymin, xmax, ymax
              box_targets = [np.array([min(box_target[:, 0]), min(box_target[:, 1]), max(
                  box_target[:, 0]), max(box_target[:, 1])], dtype=np_dtype) for box_target in box_targets] 
```
![1](https://user-images.githubusercontent.com/23098070/148366424-cc17fe99-a73b-4477-967b-bbfc3f50dd4f.png)
